# Generated by Django 5.2.7 on 2025-10-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
