# Generated by Django 5.2.7 on 2025-10-18 08:35

import django.db.models.deletion
import telegram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=telegram.models.generate_unique_token_sub, editable=False, unique=True)),
                ('days', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('activated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='telegram.telegramuser')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramuser')),
            ],
        ),
    ]
