# Generated by Django 5.2.7 on 2025-10-18 09:11

import django.db.models.deletion
import telegram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=telegram.models.generate_unique_token_token, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='telegram.telegramuser')),
            ],
        ),
    ]
